### ISSUE TITLE
No internet connection issue

### ISSUE THREAD

**Issue by panzo19** [luksus42/soundrecog#4]
Hi 
when try to run reurn the following message
"No internet connection issue the recording has been saved. You can execute the recognition from the history again."

**Comment by luksus42** [comment]
Hi,
I am not sure if I understand your problem the right way.
The connection error appears, if the recorded sample could not be transmitted to the "recognition-server". In most cases this is caused by a missing internet connection.
So, if you are shure you have a working internet connection, while using the app, perhaps there is an issue with the api-key or server configs...

**Comment by panzo19** [comment]
HiCould you please help me?I have  put the following records in settings but unfortunately not working as shown bellow! 
Internet connection is working.



Στάλθηκε από το Ταχυδρομείο Yahoo για iPhone


Στις Παρασκευή, Αυγούστου 30, 2019, 11:25 πμ, ο χρήστης luksus42 <notifications@github.com> έγραψε:


Hi,
I am not sure if I understand your problem the right way.
The connection error appears, if the recorded sample could not be transmitted to the "recognition-server". In most cases this is caused by a missing internet connection.
So, if you are shure you have a working internet connection, while using the app, perhaps there is an issue with the api-key or server configs...

**Comment by luksus42** [comment]
Did you forget to past your settings? I don't see it in your post.

What is the host-url in your settings?
What happens, if you call that host-url from the internet browser?

**Comment by panzo19** [comment]
Hi Lukus sorry for not attached screenshotsbellow you can find my settings

 Host dentify-eu-west-1.acrcloud.com

Key 05d1cc206...
Secret MNMCmFmYvSuskso....



When im trying to connect on host the follwing message appears

Welcome to nginx!

If you see this page, the nginx web server is successfully installed and working. Further configuration is required.

For online documentation and support please refer to nginx.org.
Commercial support is available at nginx.com.
Thank you for using nginx.


Kind Regards Panos  
Did you forget to past your settings? I don't see it in your post.

What is the host-url in your settings?
What happens, if you call that host-url from the internet browser?

**Comment by luksus42** [comment]
I cut off your key and secret, because no one but you should know they.

Can you please confirm, that you are not missing the "i" in the host-url in the app settings?
-> dentify vs. identify...
Or ist just a copy and paste error here in your comment?

**Comment by panzo19** [comment]
Hi Luksusthere is no problem for the key and secret it is just a test account yes I confirm that it was a copy - paste error
the url is identify-eu-west-1.acrcloud.com
    Στις Τρίτη, 3 Σεπτεμβρίου 2019, 1:43:15 μμ EEST, ο χρήστης luksus42 <notifications@github.com> έγραψε:  
 
 
I cut off your key and secret, because no one but you should know they.

Can you please confirm, that you are not missing the "i" in the host-url in the app settings?
Or ist just a copy and paste error here in your comment?

**Comment by luksus42** [comment]
Hm.
So the only way I can force a connection issue is, when I really have no connection or I have a faulty host address... maybe there is a whitespace somewhere in your host? I am just guessing because I have no better idea...

As you will see in your acrcloud account stats, I just did a successful request.

**Comment by luksus42** [comment]
Are there recordings in the history at all?
Are you able to play them back?

**Comment by panzo19** [comment]
Hmmm maybe i must contact ACRC i have already try from different pcs but withiut any luck,yes i can play the recordings from history    Στις Τρίτη, 3 Σεπτεμβρίου 2019, 10:32:21 μ.μ. EEST, ο χρήστης luksus42 <notifications@github.com> έγραψε:  
 
 
Are there recordings in the history at all?
Are you able to play them back?

**Comment by luksus42** [comment]
ahh, are you trying from a pc (browser) not from a ubports phone?
Then the problem maybe is "cross-site-scripting" (CORS).

**Comment by panzo19** [comment]
Yes im trying from pc browser.is there any way to solve the CORS issue?    Στις Τετάρτη, 4 Σεπτεμβρίου 2019, 09:52:41 π.μ. EEST, ο χρήστης luksus42 <notifications@github.com> έγραψε:  
 
 
ahh, are you trying from a pc (browser) not from a ubports phone?
Then the problem maybe is "cross-site-scripting" (CORS).

**Comment by luksus42** [comment]
Ok, happy to know th problm now. :-)

Yes you could try with google chrome, starting it from the terminal/commandline:
https://alfilatov.com/posts/run-chrome-without-cors/

Other instances of the browser needs to be closed before starting it with the special options to make it work.

**Comment by panzo19** [comment]
Hey Luskus thanks a lot for the support!! It means that it works now!


Στάλθηκε από το Ταχυδρομείο Yahoo για iPhone


Στις Τετάρτη, Σεπτεμβρίου 4, 2019, 10:04 πμ, ο χρήστης luksus42 <notifications@github.com> έγραψε:


Ok, happy to know th problm now. :-)

Yes you could try with google chrome, starting it from the terminal/commandline:
https://alfilatov.com/posts/run-chrome-without-cors/

Other instances of the browser needs to be closed before starting it with the special options to make it work.

**Comment by luksus42** [comment]
I am glad that it works now.

**Comment by luksus42** [comment]
I am glad that it works now.
