### ISSUE TITLE
App not working on VollaPhone

### ISSUE THREAD

**Issue by stanwood77** [luksus42/soundrecog#5]
I'm using Music Recognition on my Nexus 5, and it works perfectly well. (Awesome app! :-)
However, it doesn't work with the Vollaphone (Halium 9 / arm64). 
By pressing the green microphone touch to start recording, nothing happens (unresponsive key)
Thank you very much for your attention.
Cheers,

Steve

**Comment by luksus42** [comment]
Hi Steve,
thanks for the report.
Could you please check your app microphone authorizations in system-settings/security ?

![screenshot20201221_130801282](https://user-images.githubusercontent.com/6659488/102775939-2760bb80-438e-11eb-8635-295923f386de.png)

Somehow for me it was (also) disabled here.

**Comment by stanwood77** [comment]
Hi,

Thank you for your answer.
I confirm that Music Recognition doesn't appear in the menu settings => apps authorizations (picture 2)
despite I did accept the app to access to the microphone (picture 1).
Thank you beforehand for your help.

Steve
![Music recognition1](https://user-images.githubusercontent.com/62994815/102813014-601d8680-43c8-11eb-81cf-07cf06ce7efd.jpg)
![Music Recognition2](https://user-images.githubusercontent.com/62994815/102813015-60b61d00-43c8-11eb-8073-77102ec4f716.jpg)

**Comment by luksus42** [comment]
Hm, I I don't know what is the issue then.
I am also using an arm64 android-9 phone... so this can not be the issue.

Perhaps try to clear all cache and such with UT Tweak Tool and reinstall the app, to get the system settings to recognize it.

**Comment by stanwood77** [comment]
Thank you. 
I did this twice, (and reboot each time) unfortunately problem persist, even if I allow the permission by opening the app, microphone button does not react. App does not appear in the security settings.
Maybe is this issue specific to the VollaPhone? I just edit the title accordingly. 
Cheers

**Comment by luksus42** [comment]
Yeah, maybe.
Which channel (stable, rc, devel) do you use?

**Comment by stanwood77** [comment]
OTA-15 Stable

**Comment by luksus42** [comment]
Mh, I have currently no idea, what could be the cause.
I am using a dev-build from some weeks ago... I will update my phone and see if it is reproducible for me.

**Comment by stanwood77** [comment]
I'm embarrassed to bother you with this issue. You did react very quickly ;-) 
This app works great on my Nexus 5 however...
Thanks so much for having taking time for this. Maybe it will be solved in a future update of the Vollaphone...

**Comment by stanwood77** [comment]
After several manipulations in the recovery Bootloader, finally MR started to work. I close the issue. Thank you for your help.
