### ISSUE TITLE
Microphone not working

### ISSUE THREAD

**Issue by EgleaphIL** [luksus42/soundrecog#6]
I created the account and the project.
Then passed all the keys into the app, i also clicked yes to authorise the microphone.

When i click nothing happens, in system there are no authorised app.

I have a nexus 5 on UT

Thanks for the help

**Comment by luksus42** [comment]
Hi,
Could you please try to activate the "Demo Mode" in settings and tell me if then something happens?

**Comment by EgleaphIL** [comment]
> Hi,
> Could you please try to activate the "Demo Mode" in settings and tell me if then something happens?

Hi, thanks for your reply.
It did not happen anythink.

Actually i could not use the microphone for any app. No recording nor teleports.
This app conflicts with the microphone on the nexus 5.
I reset the pbone twice and as soon as i open the app, the mic stops working.
I was forced to remove this app.

**Comment by luksus42** [comment]
You say, that this app also breaks the microphone for other apps?
On which release channel are you (dev, rc, stable)?

**Comment by EgleaphIL** [comment]
Where can I see the release channels please?

**Comment by EgleaphIL** [comment]
> You say, that this app also breaks the microphone for other apps?
> On which release channel are you (dev, rc, stable)?

Where can I see the release channels please?

**Comment by luksus42** [comment]
> Where can I see the release channels please?

System Settings/System/Updates -> Update-Settings at the bottom -> Second entry "Channel"

**Comment by luksus42** [comment]
@EgleaphIL :
I could just reproduce this issue on my BQ e4.5 in the dev channel.
I assume it has something to do with the recent update of the systems QT framework to version 5.12.
Probably I will need some time to investigate this issue.

I think in the meantime, you could just switch to the relesase candidate (RC) channel in the system settings, as I described above.

**Comment by luksus42** [comment]
@EgleaphIL:
In the next OTA, there will be a fix which prevents breaking microphone for other apps.
Meanwhile the fix is already in the dev-channel, where you could test it.
You should now be able to grant access to the Music Recognition app, in the system settings -> security -> app-permissions.
